### ISSUE TITLE
The "This Week" summary should show the unplanned committed time

### ISSUE THREAD

**Issue by orozluk** [lurume84/jirafy-desktop#5]
I am currently doing mostly unplanned work. The "This week" summary shows only the planned work reduced by me, but not the amount of unplanned work. This may cause confusion about if the work is being logged or not. I think that it would be useful to have the total amount of work logged during that day

Maybe something like this:

![imagen](https://user-images.githubusercontent.com/21236359/68689624-f4d07680-0570-11ea-9b06-984daad2b4fd.png)

**Comment by lurume84** [comment]
New jirafy-viewer release includes this feature. Combined with the previous one that shows worklog broken down in a table, it also shows the uncommitted time.
